### ISSUE TITLE
Registration failed: Error Domain=PushyRN.PushyResponseException Code=0 "(null)"

### ISSUE THREAD

**Issue by causztic** [pushy-me/pushy-demo-react-native#7]
Hello,

My company has purchased a premium plan and I followed the instructions to try out Pushy:

1. I had to upgrade react-native to 0.59.9 to get past this error: -> `React Native — Unknown argument type ‘attribute’ in method -[RCTAppState getCurrentAppState:error:]. Extend RCTConvert to support this type.`
2. Now, I have the error message in the title after some time: -> `Registration failed: Error Domain=PushyRN.PushyResponseException Code=0 "(null)"`

Any ideas?

**Comment by pushy** [comment]
Hi @causztic,
Thanks for reaching out. We'd be glad to assist.

As per the `PushyResponseException`, it is most likely due to not having [created an app in the Pushy dashboard](https://dashboard.pushy.me/apps) configured with your React Native app's **Bundle ID** and/or **Package Name**.

Please ensure you have created an app with the right Bundle ID and Package Name, and check whether the issue has been resolved.

**Comment by causztic** [comment]
Thank you, that fixed it
